# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: Check Node.js code formatting

on:
  push:
    paths:
      - '**/*.js'
      - '.github/**/*.yml'
      - '.eslintrc.json'
      - '.prettierrc'
      - 'package-lock.json'
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  eslint:
    name: Run prettier & eslint scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run configured Prettier & ESLint
        run: npm run lint
